[package]
name = "miniRtspServer"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.0"
env_logger = "0.11.5"
rand = "0.8.5"
linked-hash-map = "0.5.6"
bytes = "1.8.0"
chrono = "0.4.38"
rtsp = { path = "./rtsp" }
media = { path = "./media" }