[package]
name = "rtsp"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.0"
linked-hash-map = "0.5.6"
rand = "0.8.5"
chrono = "0.4.38"
md5 = "0.7.0"
base64 = "0.21.2"
media = { path = "../media" }